#!/bin/bash
set -e

# Make the script executable
chmod +x /usr/bin/ezrepo

echo "ezrepo has been installed."
echo "Run 'ezrepo -h' for usage information."
echo "The first time you run ezrepo, it will prompt you to set up your GitHub token."

exit 0 