name: Build and push docker images



on:
  push:
    branches: ["main"]




jobs:
  build-and-push: # Build and push docker images
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

  # Loging in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Build and push Docker images
        env:
          DOCKERREPO: testactions
          IMAGE_TAG: latest
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERREPO }}:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERREPO }}:${{ env.IMAGE_TAG }}
